### ISSUE TITLE
YuleWalker not used?

### ISSUE THREAD

**Issue by priyankrastogi** [Workday/timeseries-forecast#15]
HannanRissanen.estimateARMA() calculates "yuleWalkerParams", but these params are not used anywhere in the code.
is this a "TODO" item? or maybe YuleWalker not needed (dead code)?

**Comment by yonseokim** [comment]
Hello priyankrastogi,
The Yule-Walker algorithm is used to estimate initial error values and are used in the following iteration steps. The errors are computed and passed on in-place by the method.
Hope this clarifies your question.
