### ISSUE TITLE
predicted result gets absurdly large when deal with 10 days data

### ISSUE THREAD

**Issue by ey4295** [Workday/timeseries-forecast#16]
I set ArimaParam as (2,2,2)(1,1,1)36
The returned value is absurdly large.
My input time series data was around 7000,while the predicted values were larger than 10,000,000.
This can't be right,can any one help me?

**Comment by yonseokim** [comment]
Hello ey4295,

Do you mean you gave 10 data points? The ARIMA model has 7 parameters and 10 data points would not be sufficient to make any meaningful prediction. Please try to give more data points.
