### ISSUE TITLE
Failed to build ARIMA forecast: not enough data points: length=7, r=4

### ISSUE THREAD

**Issue by ShubhamJainSJ** [Workday/timeseries-forecast#18]
I want to generate forecast for next 3 months using last 6 months data.
I tried with 9 months data and following data but getting following error:
**"Failed to build ARIMA forecast: not enough data points: length=7, r=4"**

Data:
```
int p = 3;
int d = 0;
int q = 3;
int P = 1;
int D = 1;
int Q = 0;
int m = 0;
int forecastSize = 3;
	     
final ArimaParams paramsForecast = new ArimaParams(p, d, q, P, D, Q, m);
double[] inputData = {100.0, 50.0, 100.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};

ForecastResult forecastResult = Arima.forecast_arima(inputData, forecastSize, paramsForecast);
double[] predictedData = forecastResult.getForecast(); 


```

Any solution for this?

**Comment by yonseokim** [comment]
Hello ShubhamJainSJ,

ARIMA model has 7 parameters and 7 data points would be too little information to fit any model on it. Please try to give more data points.
